# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('base_url', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('link_url', models.CharField(help_text='URL or URI to the content, eg /about/ or http://foo.com/', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Menu')),
            ],
        ),
        migrations.AddField(
            model_name='language',
            name='lan_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Menu'),
        ),
        migrations.AddField(
            model_name='language',
            name='lan_submenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.SubMenu'),
        ),
    ]
