# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20160610_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='lan_menu',
        ),
        migrations.RemoveField(
            model_name='language',
            name='lan_submenu',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
