# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20160610_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='description',
            new_name='data',
        ),
        migrations.AddField(
            model_name='submenu',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
