# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_context_context_lan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.RemoveField(
            model_name='context',
            name='images',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='prop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.Context'),
        ),
    ]
