# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20160612_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='title3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='context',
            name='title4',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='context',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='context',
            name='title2',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
