# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20160612_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Menu'),
        ),
        migrations.AlterField(
            model_name='context',
            name='submenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.SubMenu'),
        ),
    ]
