# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
