# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20160612_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenu',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='title',
        ),
        migrations.AddField(
            model_name='submenu',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
