# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='prof',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
