# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_personal_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='slug',
            field=models.SlugField(blank=True, max_length=40),
        ),
    ]
