# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20160614_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='context',
            name='text2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
