# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_personal_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(upload_to=b'')),
                ('articlecontext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ArticleContext')),
            ],
        ),
    ]
