# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_auto_20160615_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecontext',
            name='article_lan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Language'),
        ),
        migrations.AlterField(
            model_name='images',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
