# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_auto_20160615_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='articlecontext',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.ArticleContext'),
        ),
    ]
