# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_auto_20160615_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='articlecontext',
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='Image1',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='Image10',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='Image11',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='Image12',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='Image13',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='Image14',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='Image2',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='Image3',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='Image4',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='Image5',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='Image6',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='Image7',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='Image8',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='Image9',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
