# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_auto_20160615_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecontext',
            name='text5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
