# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_articlecontext_title4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecontext',
            name='Image1',
        ),
        migrations.RemoveField(
            model_name='articlecontext',
            name='Image10',
        ),
        migrations.RemoveField(
            model_name='articlecontext',
            name='Image11',
        ),
        migrations.RemoveField(
            model_name='articlecontext',
            name='Image12',
        ),
        migrations.RemoveField(
            model_name='articlecontext',
            name='Image13',
        ),
        migrations.RemoveField(
            model_name='articlecontext',
            name='Image14',
        ),
        migrations.RemoveField(
            model_name='articlecontext',
            name='Image2',
        ),
        migrations.RemoveField(
            model_name='articlecontext',
            name='Image3',
        ),
        migrations.RemoveField(
            model_name='articlecontext',
            name='Image4',
        ),
        migrations.RemoveField(
            model_name='articlecontext',
            name='Image5',
        ),
        migrations.RemoveField(
            model_name='articlecontext',
            name='Image6',
        ),
        migrations.RemoveField(
            model_name='articlecontext',
            name='Image7',
        ),
        migrations.RemoveField(
            model_name='articlecontext',
            name='Image8',
        ),
        migrations.RemoveField(
            model_name='articlecontext',
            name='Image9',
        ),
    ]
