# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_articlecontext_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecontext',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
