# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_auto_20160615_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecontext',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='image4',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='image5',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='articlecontext',
            name='image6',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
