# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_auto_20160615_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecontext',
            name='image7',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
