# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_lan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Language'),
        ),
    ]
