# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_services_service_lan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_text', models.CharField(max_length=250)),
                ('image', models.FileField(blank=True, null=True, upload_to=b'')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Gallery')),
            ],
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_lan',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
