# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_auto_20160615_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='question_text',
            new_name='text',
        ),
    ]
