# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0042_auto_20160616_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='data3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='image8',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='submenu',
            name='title3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='title2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
