# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0043_auto_20160616_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenu',
            name='data2',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='data3',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='title3',
        ),
    ]
