# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_servicesmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesmodel',
            name='services_lan',
        ),
        migrations.DeleteModel(
            name='ServicesModel',
        ),
    ]
