# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0047_auto_20160616_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
